[project]
name = "mangaflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "deepl>=1.12.0",
    "googletrans==4.0.0rc1",
    "manga-ocr>=0.1.8",
    "matplotlib>=3.5.0",
    "numpy==1.24.3",
    "opencv-python-headless==4.8.1.78",
    "pillow==10.2.0",
    "python-dotenv>=1.0.0",
    "streamlit==1.31.1",
    "torch>=2.1.0",
    "torchvision>=0.16.0",
    "transformers>=4.30.0",
    "ultralytics>=8.0.0",
]
